SV-1142 - Admin service actioning EPAO register withdrawal and automated withdrawal
SkillsFundingAgency/das-admin-service pull request #296
Opened 2021-08-16 13:09 UTC by StuartReeve102

2021-08-18 12:43 UTC, alandburns approved these changes
Tested locally, and looks OK to me.

2021-08-19 13:35 UTC, CodeWolf86 requested changes

2021-08-19 13:35 UTC, CodeWolf86 commented on src/SFA.DAS.AdminService.Web/Views/Application/Returned.cshtml
> +                            <li>You'll need to manually remove this organisation from the register of end-point assessment organisations on the agreed date.</li>
I think this content for withdraw from the register and withdraw from a standard is wrong. Both refer to manually removing the organisation which now shouldn't be needed i think?

2021-08-20 09:39 UTC, CodeWolf86 approved these changes

2021-08-20 09:40 UTC, merged