Sv 889 handle reapplies for withdrawn standard admin svc
SkillsFundingAgency/das-admin-service pull request #324
Opened 2022-01-05 01:31 UTC by anilkdhiman6

2022-01-06 17:00 UTC, CodeWolf86 requested changes
There are no unit tests added for this against the ApplicationController. It's one of the key controllers in the admin service so I'd like to see some against the new code.

2022-01-06 21:34 UTC, anilkdhiman6 commented on src/SFA.DAS.AdminService.Web/ViewModels/Apply/Applications/SequenceViewModel.cs
> +                        }
Yes - this is a typo - should be:

```
     if (application.ApplyData.Apply.Versions.Contains(ver))
           return withdrawal;
```

However have refactored to improve readability.

2022-01-06 21:35 UTC, anilkdhiman6 commented on src/SFA.DAS.AdminService.Web/ViewModels/Apply/Applications/SequenceViewModel.cs
> +                        if (withdrawal.ApplicationType == StandardApplicationTypes.StandardWithdrawalApp)
Previous Withdrawals are returned ordered by **CreatedAt** from the SQL Query.

Have refactored this method

2022-01-06 21:36 UTC, anilkdhiman6 commented on src/SFA.DAS.AdminService.Web/Controllers/Apply/ApplicationController.cs
> +            var withdrawal = await _applyApiClient.GetWithdrawnApplications(application.OrganisationId, application.StandardCode);
Can we catch up regarding the logic for this please  @CodeWolf86

2022-01-11 00:46 UTC, anilkdhiman6 commented on src/SFA.DAS.AdminService.Web/Controllers/Apply/ApplicationController.cs
> +            var withdrawal = await _applyApiClient.GetWithdrawnApplications(application.OrganisationId, application.StandardCode);
Refactored - altered as discussed

2022-01-13 13:59 UTC, CodeWolf86 approved these changes

2022-02-10 16:58 UTC, CodeWolf86 approved these changes

2022-02-16 09:57 UTC, merged