CSP-379-TribalRole-Accessing-Manage-Provider-Description
SkillsFundingAgency/das-admin-service pull request #355
Opened 2022-11-24 16:44 UTC by raviudari01

2022-11-25 10:00 UTC, MarkFCain approved these changes

2022-11-28 10:56 UTC, DevenKShah requested changes

2022-11-28 10:56 UTC, DevenKShah commented on src/SFA.DAS.AdminService.Web/Views/SearchTrainingProvider/Index.cshtml
> +﻿@using SFA.DAS.AdminService.Web.Controllers
This view is going to be part of QA site. Remove this.

2022-11-28 10:56 UTC, DevenKShah commented on src/SFA.DAS.AdminService.Web/Controllers/SearchTrainingProviderController.cs
> +    [Authorize(Roles = Domain.Roles.TribalTeam)]
This controller is not supposed to be in here. We need to put a link to web qa instead,

2022-12-23 14:55 UTC, MarkFCain approved these changes

2022-12-23 15:37 UTC, merged